<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FootballLeagueResults [
  <!ELEMENT FootballLeagueResults (Game*)>
  <!ELEMENT Game (LocalTeam, VisitingTeam)>
  <!ELEMENT LocalTeam (#PCDATA)>
  <!ELEMENT VisitingTeam (#PCDATA)>
  <!ATTLIST Game
    LocalGoals CDATA #REQUIRED
    VisitingGoals CDATA #REQUIRED
  >
]>

<FootballLeagueResults>
  <Game LocalGoals="0" VisitingGoals="1">
    <LocalTeam>Nottingham Preesa</LocalTeam>
    <VisitingTeam>Inter from Mitente</VisitingTeam>
  </Game>
  <Game LocalGoals="3" VisitingGoals="3">
    <LocalTeam>Vodka Juniors</LocalTeam>
    <VisitingTeam>Sparta da Risa</VisitingTeam>
  </Game>
  <Game LocalGoals="4" VisitingGoals="2">
    <LocalTeam>Water of Munich</LocalTeam>
    <VisitingTeam>Esteaua is from the tap</VisitingTeam>
  </Game>
</FootballLeagueResults>